/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-calendar/calendar-client/assets/org.lingmo.calendar.metainfo.xml -a ./dde-calendar/toolGenerate/qdbusxml2cpp/org.lingmo.calendar.metainfoAdaptor -i ./dde-calendar/toolGenerate/qdbusxml2cpp/org.lingmo.calendar.metainfo.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-calendar/toolGenerate/qdbusxml2cpp/org.lingmo.calendar.metainfoAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

